INSERT INTO BOOKS(ID,AUTHOR,ISBN,PUBLISH_DATA,TITLE)VALUES(1,'TEST AUTHOR','TESTISBN','2001-01-01','TEST KİTAP1');
INSERT INTO BOOKS(ID,AUTHOR,ISBN,PUBLISH_DATA,TITLE)VALUES(2,'TEST AUTHOR1','TESTISBN2','2001-01-01','TEST KİTAP2');
INSERT INTO BOOKS(ID,AUTHOR,ISBN,PUBLISH_DATA,TITLE)VALUES(3,'TEST AUTHOR2','TESTISBN3','2001-01-01','TEST KİTAP3');